const SET_USER = "SET_USER";
const CLEAR_USER = "CLEAR_USER";

const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";

export { SET_USER, CLEAR_USER, SET_CURRENT_CHANNEL, SET_PRIVATE_CHANNEL };
